spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: false
server:
  port: 8088
